# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pcp < Formula
  desc "pcp is a command line peer-to-peer data transfer tool based on libp2p"
  homepage "https://github.com/dennis-tra/pcp"
  version "0.3.2"
  license "Apache License Version 2.0"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/dennis-tra/pcp/releases/download/v0.3.2/pcp_0.3.2_darwin_amd64.tar.gz"
    sha256 "23a71dfff09721d5ab3e3482a4403291b50f342c28a47d43acfdd3d8c313b705"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/dennis-tra/pcp/releases/download/v0.3.2/pcp_0.3.2_linux_amd64.tar.gz"
    sha256 "8fbfcdba2363e3a033b8fa7457f09869a0b808d4ef5da41a9a4eae9a41ebcddd"
  end

  def install
    bin.install "pcp"
  end
end
