# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pcp < Formula
  desc "pcp is a command line peer-to-peer data transfer tool based on libp2p."
  homepage "https://github.com/dennis-tra/pcp"
  version "0.3.2"
  license "Apache License Version 2.0"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/dennis-tra/pcp/releases/download/v0.3.2/pcp_0.3.2_macos_amd64.tar.gz"
    sha256 "146bdb2fea85d91246011c5fda01943839ab91a5120ceab9e3fcec0c589cc92a"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/dennis-tra/pcp/releases/download/v0.3.2/pcp_0.3.2_linux_amd64.tar.gz"
    sha256 "d65b9667707572eb9008bdea800663ca836d2ef2834c9425a720318902e7ee3c"
  end

  def install
    bin.install "pcp"
  end

  test do
    system "#{bin}/croc --version"
  end
end
