# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pcp < Formula
  desc "pcp is a command line peer-to-peer data transfer tool based on libp2p"
  homepage "https://github.com/dennis-tra/pcp"
  version "0.3.2"
  license "Apache License Version 2.0"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/dennis-tra/pcp/releases/download/v0.3.2/pcp_0.3.2_macos-amd64.tar.gz"
    sha256 "add3ed66ba6f71de26865bde05b4254ed404a3f01c3f58778ef3f111fdbc9629"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/dennis-tra/pcp/releases/download/v0.3.2/pcp_0.3.2_linux-amd64.tar.gz"
    sha256 "42e733c05480cfc6ea6a7ebb0600129a83957df90636b17115ceb2caf018ed8d"
  end

  def install
    bin.install "pcp"
  end
end
