# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pcp < Formula
  desc "pcp is a command line peer-to-peer data transfer tool based on libp2p."
  homepage "https://github.com/dennis-tra/pcp"
  version "0.4.0"
  license "Apache License Version 2.0"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/dennis-tra/pcp/releases/download/v0.4.0/pcp_0.4.0_macos_amd64.tar.gz"
    sha256 "a053ea9c1e2e1af98e8773c3f0a91e9191b961b41b2921277235de30467f2e88"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/dennis-tra/pcp/releases/download/v0.4.0/pcp_0.4.0_macos_arm64.tar.gz"
    sha256 "22452930ccd3537a0e734b6ecd99521683bdbee13b75c7b691f69f8ca5176ed2"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/dennis-tra/pcp/releases/download/v0.4.0/pcp_0.4.0_linux_amd64.tar.gz"
    sha256 "4727917b4ea54a318d8ef84fba1c364505796fd011213202fcdba71b19d33b82"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/dennis-tra/pcp/releases/download/v0.4.0/pcp_0.4.0_linux_armv6.tar.gz"
    sha256 "c9103cac6970bbe92d3e24dc9bb80f1d4005dd7531c524f8e5c564c8b406ee94"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/dennis-tra/pcp/releases/download/v0.4.0/pcp_0.4.0_linux_arm64.tar.gz"
    sha256 "58fa4a2f613f21dc9bd5a298f15d69204ba874f2018fb52237ddce7c1d439cae"
  end

  def install
    bin.install "pcp"
  end

  test do
    system "#{bin}/croc --version"
  end
end
