# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pcp < Formula
  desc "pcp is a command line peer-to-peer data transfer tool based on libp2p."
  homepage "https://github.com/dennis-tra/pcp"
  version "0.4.0-rc1"
  license "Apache License Version 2.0"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/dennis-tra/pcp/releases/download/v0.4.0-rc1/pcp_0.4.0-rc1_macos_amd64.tar.gz"
    sha256 "ee6c1efa24ab5d952bda0b00f5182f7f7a1fd9fdf5ed4dcd5adddc9035f96b10"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/dennis-tra/pcp/releases/download/v0.4.0-rc1/pcp_0.4.0-rc1_macos_arm64.tar.gz"
    sha256 "d744551f2144055712ea298f2fde7768bdfd019d7f7c8b39b82d64406ca5b460"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/dennis-tra/pcp/releases/download/v0.4.0-rc1/pcp_0.4.0-rc1_linux_amd64.tar.gz"
    sha256 "d16e767d02badf1763252ec617bdf8e662bae44caded9b9b7ccaeae79ec66ea1"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/dennis-tra/pcp/releases/download/v0.4.0-rc1/pcp_0.4.0-rc1_linux_armv6.tar.gz"
    sha256 "514bff5c38a722d66aee3cff2bb6b6035c6cceff639f5db209358b850921766d"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/dennis-tra/pcp/releases/download/v0.4.0-rc1/pcp_0.4.0-rc1_linux_arm64.tar.gz"
    sha256 "b0b06dfb80873c4a433339d0b44a91e3d91e2f4a9bf6ea0d1b0a0f7ae5276159"
  end

  def install
    bin.install "pcp"
  end

  test do
    system "#{bin}/croc --version"
  end
end
